resource "aws_bedrock_guardrail" "guardrail" {
  name                      = "bedrock-guards"
  blocked_input_messaging   = "Information you shared doesn't follow our AI policy."
  blocked_outputs_messaging = "Information generated by the AI doesn't follow our AI policy."
  description               = "Bedrock ethical and safe AI guardrails"

  content_policy_config {
    filters_config {
      input_strength  = "HIGH"
      output_strength = "HIGH"
      type            = "HATE"
    }
    filters_config {
      input_strength  = "HIGH"
      output_strength = "HIGH"
      type            = "INSULTS"
    }
    filters_config {
      input_strength  = "HIGH"
      output_strength = "HIGH"
      type            = "SEXUAL"
    }
    filters_config {
      input_strength  = "HIGH"
      output_strength = "HIGH"
      type            = "VIOLENCE"
    }
    filters_config {
      input_strength  = "HIGH"
      output_strength = "HIGH"
      type            = "MISCONDUCT"
    }
  }

  word_policy_config {
    managed_word_lists_config {
      type = "PROFANITY"
    }
    words_config {
      text = "HATE"
    }
  }
}

resource "aws_bedrock_guardrail_version" "guardrail_version" {
  description   = "guardrail version"
  guardrail_arn = aws_bedrock_guardrail.guardrail.guardrail_arn
}